### ISSUE TITLE
The Readme file is changed and SP0204 files are added to the main directory

### ISSUE THREAD

**Issue by Siddharthgolecha** [dscmbm/StudyPods-v2.0#62]
**Describe the bug**
The main README.md file has been changed and the commit by SP0204 was not properly done and reviewed. @Khushipurohit you added the file at the wrong place and @Anuraggupta3979 you did not properly review the changes before merging the request. Please review the changes first properly without merging it

**Comment by Satwikan** [comment]
Can you confirm the pull request numbet @Siddharthgolecha which @Anuraggupta3979 accepted by which those files were added so I can review it.

**Comment by Siddharthgolecha** [comment]
Original README.md file restored.
